# Configurações do Servidor
server.port=${PORT:8080}

# Configurações de Conexão com o Banco H2
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria e atualiza as tabelas automaticamente com base nas classes Java
spring.jpa.hibernate.ddl-auto=update

# Habilita o Console do H2 no navegador (Para você ver o banco rodando)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra no console os comandos SQL que o Hibernate está executando por baixo dos panos
spring.jpa.show-sql=true